_wandb:
    value:
        cli_version: 0.25.0
        e:
            7x2zcjlgc47b09wiooq24p96lakcrvop:
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "134865883136"
                        used: "1944027136"
                email: jana3@wisc.edu
                executable: /global/homes/a/aneekj02/.conda/envs/colliderml-env/bin/python
                git:
                    commit: 5b03fe3ec59f564257ce06d3bb0543852571513b
                    remote: git@github.com:imaneekjana/hep-ssl.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-1dcf15e2-79c0-cb41-a293-281882cdaaa9
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-678e897d-2548-e80e-5579-b9009d8c1bb2
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-069ededc-6f93-394d-0c35-01a1c3cf08db
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-cd062331-49f4-57c0-bf4c-9f916cbfc84e
                host: nid001069
                memory:
                    total: "269731766272"
                os: Linux-6.4.0-150600.23.92_15.0.23-cray_shasta_c-x86_64-with-glibc2.38
                program: -m src.train_gnn_colliderml_3
                python: CPython 3.11.14
                root: /global/cfs/cdirs/m4474/aneek/particlemind_aneek
                slurm:
                    cluster_name: perlmutter
                    cpus_on_node: "128"
                    cpus_per_task: "128"
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: m4474_g
                    job_cpus_per_node: "128"
                    job_end_time: "1779949546"
                    job_gid: "111790"
                    job_gpus: 0,1,2,3
                    job_id: "53501572"
                    job_licenses: cfs:1
                    job_name: jupyter
                    job_nodelist: nid001069
                    job_num_nodes: "1"
                    job_partition: urgent_gpu_ss11
                    job_qos: gpu_jupyter
                    job_start_time: "1779927946"
                    job_uid: "111790"
                    job_user: aneekj02
                    jobid: "53501572"
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid001069
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nid001069
                    submit_dir: /global/cfs/cdirs/m4474/aneek
                    submit_host: login11
                    task_pid: "164143"
                    tasks_per_node: "1"
                    topology_addr: global.group5.nid001069
                    topology_addr_pattern: switch.switch.node
                    tres_bind: gres/gpu:per_task:4
                    tres_per_task: cpu=128,gres/gpu=4
                startedAt: "2026-05-28T00:45:30.788321Z"
                writerId: 7x2zcjlgc47b09wiooq24p96lakcrvop
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 77
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 77
            "3":
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 32
device:
    value: cuda
disable_cuda:
    value: false
energy_noise:
    value: 0.05
epochs:
    value: 18
feat_dim:
    value: 4
fp16_precision:
    value: false
gpu_index:
    value: 0
log_every_n_steps:
    value: 100
lr:
    value: 0.0003
n_views:
    value: 2
"off":
    value: 0
out_dim:
    value: 32
rotation:
    value: 0.39269908169872414
seed:
    value: 42
split:
    value: dihiggs_scale_5.0_gaussian
temperature:
    value: 0.07
trainevents:
    value: 750
weight_decay:
    value: 0.0001
workers:
    value: 12
