universe = vanilla

executable = run_random_classifier.sh
arguments = $(output_name) $(reference_experiment)

log = random_classifier_$(Cluster)_$(Process)_$(output_name).log
output = random_classifier_$(Cluster)_$(Process)_$(output_name).out
error = random_classifier_$(Cluster)_$(Process)_$(output_name).err

should_transfer_files = YES
when_to_transfer_output = ON_SUCCESS
success_exit_code = 0

container_image = file:///staging/k/kli398/hep_ssl.sif

transfer_input_files = hep_ssl-code.tar.gz, ../2026_08_12/result_$(reference_experiment).tar.gz, osdf:///chtc/staging/k/kli398/colliderml-data-pairwise-2500.tar.gz

transfer_output_files = result_classifier_$(output_name).tar.gz

requirements = (HasCHTCStaging == true)

+WantGPULab = true
+GPUJobLength = "short"
+JobBatchName = "pairwise_random_classifiers_20260815"

request_gpus = 1
request_cpus = 2
request_memory = 64GB
request_disk = 30GB

experiment_file = random_experiments.txt

queue output_name, reference_experiment from $(experiment_file)