_wandb:
    value:
        cli_version: 0.25.0
        e:
            5cl2ein09aeb8exzkwk748ldwclzlwb2:
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "134865858560"
                        used: "612593664"
                email: jana3@wisc.edu
                executable: /global/homes/a/aneekj02/.conda/envs/colliderml-env/bin/python
                git:
                    commit: 5b03fe3ec59f564257ce06d3bb0543852571513b
                    remote: git@github.com:imaneekjana/hep-ssl.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-aa8c68d7-d2e0-a2c0-38ad-986bc81f1d51
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-681c09a6-df8f-9d38-df3a-7a7b07164ca5
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-0a18bc35-a99e-b80a-75b4-90734e7fbe55
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-ea9f1fb3-0dbf-f6bd-89df-d72a0bd9aa08
                host: nid001016
                memory:
                    total: "269731717120"
                os: Linux-6.4.0-150600.23.73_15.0.14-cray_shasta_c-x86_64-with-glibc2.38
                program: <python with no main file>
                python: CPython 3.11.14
                root: /global/cfs/cdirs/m4474/aneek/particlemind_aneek/notebooks
                slurm:
                    cluster_name: perlmutter
                    cpus_on_node: "128"
                    cpus_per_task: "128"
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: m4474_g
                    job_cpus_per_node: "128"
                    job_end_time: "1774036918"
                    job_gid: "111790"
                    job_gpus: 0,1,2,3
                    job_id: "50295178"
                    job_licenses: cfs:1
                    job_name: jupyter
                    job_nodelist: nid001016
                    job_num_nodes: "1"
                    job_partition: urgent_gpu_ss11
                    job_qos: gpu_jupyter
                    job_start_time: "1774015318"
                    job_uid: "111790"
                    job_user: aneekj02
                    jobid: "50295178"
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid001016
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nid001016
                    submit_dir: /global/cfs/cdirs/m4474/aneek
                    submit_host: login27
                    task_pid: "709353"
                    tasks_per_node: "1"
                    topology_addr: global.group5.nid001016
                    topology_addr_pattern: switch.switch.node
                    tres_bind: gres/gpu:per_task:4
                    tres_per_task: cpu=128,gres/gpu=4
                startedAt: "2026-03-20T14:10:22.365574Z"
                writerId: 5cl2ein09aeb8exzkwk748ldwclzlwb2
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 77
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 77
            "3":
                - 2
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 32
device:
    value: cuda
disable_cuda:
    value: false
epochs:
    value: 3
feat_dim:
    value: 32
fp16_precision:
    value: false
gpu_index:
    value: 0
log_every_n_steps:
    value: 100
lr:
    value: 0.0003
n_views:
    value: 2
out_dim:
    value: 16
seed:
    value: null
temperature:
    value: 0.07
weight_decay:
    value: 0.0001
workers:
    value: 12
